In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv('Cleaned_data.csv')

In [3]:
df.drop('Unnamed: 0' , axis = 1 , inplace = True)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Company      1303 non-null   str
 1   TypeName     1303 non-null   str
 2   Cpu          1303 non-null   str
 3   Ram          1303 non-null   int64
 4   Gpu          1303 non-null   str
 5   OpSys        1303 non-null   str
 6   Weight       1303 non-null   float64
 7   Price        1303 non-null   int64
 8   TouchScreen  1303 non-null   int64
 9   IPS          1303 non-null   int64
 10  ppi          1303 non-null   int64
dtypes: float64(1), int64(5), str(5)
memory usage: 112.1 KB

In [5]:
df.shape

(1303, 11)

In [6]:
df

,Company,TypeName,Cpu,Ram,Gpu,OpSys,Weight,Price,TouchScreen,IPS,ppi
0,Apple,Ultrabook,Intel Core i5,8,Intel Iris,Mac OS,1.37,148093,0,1,227
1,Apple,Ultrabook,Intel Core i5,8,Intel HD,Mac OS,1.34,99318,0,0,128
2,HP,Notebook,Intel Core i5,8,Intel HD,No OS,1.86,63595,0,0,141
3,Apple,Ultrabook,Intel Core i7,16,AMD Radeon,Mac OS,1.83,280592,0,1,221
4,Apple,Ultrabook,Intel Core i5,8,Intel Iris,Mac OS,1.37,199411,0,1,227
...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,2 in 1 Convertible,Intel Core i7,4,Intel HD,Windows 10,1.80,70562,1,1,157
1299,Lenovo,2 in 1 Convertible,Intel Core i7,16,Intel HD,Windows 10,1.30,165789,1,1,276
1300,Lenovo,Notebook,Other Intel Processor,2,Intel HD,Windows 10,1.50,25327,0,0,112
1301,HP,Notebook,Intel Core i7,6,AMD Radeon,Windows 10,2.19,84498,0,0,100
1302,Asus,Notebook,Other Intel Processor,4,Intel HD,Windows 10,2.20,40811,0,0,100

In [7]:
df.corr(numeric_only = True)['Price']

Ram            0.743012
Weight         0.210343
Price          1.000000
TouchScreen    0.191261
IPS            0.252239
ppi            0.473620
Name: Price, dtype: float64

In [8]:
df.head()

,Company,TypeName,Cpu,Ram,Gpu,OpSys,Weight,Price,TouchScreen,IPS,ppi
0,Apple,Ultrabook,Intel Core i5,8,Intel Iris,Mac OS,1.37,148093,0,1,227
1,Apple,Ultrabook,Intel Core i5,8,Intel HD,Mac OS,1.34,99318,0,0,128
2,HP,Notebook,Intel Core i5,8,Intel HD,No OS,1.86,63595,0,0,141
3,Apple,Ultrabook,Intel Core i7,16,AMD Radeon,Mac OS,1.83,280592,0,1,221
4,Apple,Ultrabook,Intel Core i5,8,Intel Iris,Mac OS,1.37,199411,0,1,227

In [9]:
# Define the Input col
X = df.drop(columns = ['Price'])

In [10]:
# Output col
y = df['Price']

In [11]:
# Train the split
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size= 0.2 , random_state=42)

In [12]:
X_train.shape

(1042, 10)

In [13]:
X_test.shape

(261, 10)

In [14]:
y_train.shape

(1042,)

In [15]:
y_test.shape

(261,)

In [16]:
# Encoding >> OneHotEncoding

In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

In [18]:
from sklearn.linear_model import LinearRegression

In [19]:
lr = LinearRegression

In [20]:
df.sample()

,Company,TypeName,Cpu,Ram,Gpu,OpSys,Weight,Price,TouchScreen,IPS,ppi
1006,HP,Notebook,Intel Core i5,4,Intel HD,Windows 10,1.95,133273,0,0,157

In [21]:
# Linear Regression 
categorical_features = ['Company' , 'TypeName' , 'Cpu' , 'Gpu' , 'OpSys' ]

In [22]:
step1 = ColumnTransformer(transformers = [
    ('col_tnf',OneHotEncoder(sparse_output = False, handle_unknown = 'ignore'),categorical_features)
],remainder = 'passthrough')

step2 = LinearRegression()

In [23]:
pipe = Pipeline([('step1',step1),('step2',step2)])

In [24]:
# Training the model stored in Pipe
pipe.fit(X_train , y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('col_tnf',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['Company', 'TypeName', 'Cpu',
                                                   'Gpu', 'OpSys'])])),
                ('step2', LinearRegression())])

In [25]:
# Testing the model on 20% testing data & starting it for evaluation 
y_pred = pipe.predict(X_test)

In [26]:
# Evaluation Matric
# MSE
# MAE
# r2_Score

In [27]:
from sklearn.metrics import r2_score , mean_absolute_error , mean_squared_error

In [28]:
print("R_2 Score" ,r2_score(y_test,y_pred))

R_2 Score 0.7549249121531353

In [29]:
print("Mean Absolute Error",mean_absolute_error(y_test,y_pred))
print("Mean Squared Error",mean_squared_error(y_test,y_pred))

Mean Absolute Error 26990.173184951662
Mean Squared Error 1522642443.8631952

In [30]:
# Desicion tree
# Random forest

In [31]:
df

,Company,TypeName,Cpu,Ram,Gpu,OpSys,Weight,Price,TouchScreen,IPS,ppi
0,Apple,Ultrabook,Intel Core i5,8,Intel Iris,Mac OS,1.37,148093,0,1,227
1,Apple,Ultrabook,Intel Core i5,8,Intel HD,Mac OS,1.34,99318,0,0,128
2,HP,Notebook,Intel Core i5,8,Intel HD,No OS,1.86,63595,0,0,141
3,Apple,Ultrabook,Intel Core i7,16,AMD Radeon,Mac OS,1.83,280592,0,1,221
4,Apple,Ultrabook,Intel Core i5,8,Intel Iris,Mac OS,1.37,199411,0,1,227
...,...,...,...,...,...,...,...,...,...,...,...
1298,Lenovo,2 in 1 Convertible,Intel Core i7,4,Intel HD,Windows 10,1.80,70562,1,1,157
1299,Lenovo,2 in 1 Convertible,Intel Core i7,16,Intel HD,Windows 10,1.30,165789,1,1,276
1300,Lenovo,Notebook,Other Intel Processor,2,Intel HD,Windows 10,1.50,25327,0,0,112
1301,HP,Notebook,Intel Core i7,6,AMD Radeon,Windows 10,2.19,84498,0,0,100
1302,Asus,Notebook,Other Intel Processor,4,Intel HD,Windows 10,2.20,40811,0,0,100

In [32]:
y_pred.shape

(261,)

In [33]:
# KNN regressor
# Decision Tree
# Random Forest 
# XG Boost

In [34]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from xgboost import XGBRegressor

In [35]:
# KNN
step1 = ColumnTransformer(transformers = [
    ('col_tnf',OneHotEncoder(sparse_output = False, handle_unknown = 'ignore'),categorical_features)
],remainder = 'passthrough')

step2 = KNeighborsRegressor()

pipe = Pipeline([('step1',step1),('step2',step2)])
 
# Training the model stored in Pipe
pipe.fit(X_train , y_train)
y_pred = pipe.predict(X_test) #Storing the Pred made by the machine
print("R_2 Score for KNeighborsRegressor",r2_score(y_test,y_pred))
print("Mean Absoluute Error for KNeighborsRegressor",mean_absolute_error(y_test,y_pred))
print("Mean Squared Error for KNeighborsRegressor",mean_squared_error(y_test,y_pred))

R_2 Score for KNeighborsRegressor 0.7032666936738432
Mean Absoluute Error for KNeighborsRegressor 25978.82298850575
Mean Squared Error for KNeighborsRegressor 1843593041.9920309

In [36]:
#  DecisionTreeRegressor
step1 = ColumnTransformer(transformers = [
    ('col_tnf',OneHotEncoder(sparse_output = False, handle_unknown = 'ignore'),categorical_features)
],remainder = 'passthrough')

step2 = DecisionTreeRegressor(max_depth = 25 , random_state = 42)

pipe = Pipeline([('step1',step1),('step2',step2)])
 
# Training the model stored in Pipe
pipe.fit(X_train , y_train)
y_pred = pipe.predict(X_test)
print("R_2 Score for DecisionTreeRegressor",r2_score(y_test,y_pred))
print("Mean Absoluute Error for DecisionTreeRegressor",mean_absolute_error(y_test,y_pred))
print("Mean Squared Error for DecisionTreeRegressor",mean_squared_error(y_test,y_pred))

R_2 Score for DecisionTreeRegressor 0.7161316831835518
Mean Absoluute Error for DecisionTreeRegressor 27069.957662835248
Mean Squared Error for DecisionTreeRegressor 1763663338.6532025

In [37]:
# RandomForestRegressor
step1 = ColumnTransformer(transformers = [
    ('col_tnf',OneHotEncoder(sparse_output = False, handle_unknown = 'ignore'),categorical_features)
],remainder = 'passthrough')

step2 = RandomForestRegressor(n_estimators=200)

pipe = Pipeline([('step1',step1),('step2',step2)])
 
# Training the model stored in Pipe
pipe.fit(X_train , y_train)
y_pred = pipe.predict(X_test)
print("R_2 Score for RandomForestRegressor",r2_score(y_test,y_pred))
print("Mean Absoluute Error for RandomForestRegressor",mean_absolute_error(y_test,y_pred))
print("Mean Squared Error for RandomForestRegressor",mean_squared_error(y_test,y_pred))

R_2 Score for RandomForestRegressor 0.7865596981842428
Mean Absoluute Error for RandomForestRegressor 21963.384596682958
Mean Squared Error for RandomForestRegressor 1326096689.920253

In [40]:
step1 = ColumnTransformer(transformers = [
    ('col_tnf',OneHotEncoder(sparse_output = False, handle_unknown = 'ignore'),categorical_features)
],remainder = 'passthrough')

step2 =GradientBoostingRegressor(n_estimators = 500)

pipe = Pipeline([('step1',step1),('step2',step2)])
 
# Training the model stored in Pipe
pipe.fit(X_train , y_train)
y_pred = pipe.predict(X_test) #Storing the Pred made by the machine
print("R_2 Score for GradientBoostingRegressor",r2_score(y_test,y_pred))
print("Mean Absoluute Error for GradientBoostingRegressor",mean_absolute_error(y_test,y_pred))
print("Mean Squared Error for GradientBoostingRegressor",mean_squared_error(y_test,y_pred))

R_2 Score for GradientBoostingRegressor 0.8413412801131389
Mean Absoluute Error for GradientBoostingRegressor 19243.70018227462
Mean Squared Error for GradientBoostingRegressor 985740750.3601018

In [39]:
step1 = ColumnTransformer(transformers = [
    ('col_tnf',OneHotEncoder(sparse_output = False, handle_unknown = 'ignore'),categorical_features)
],remainder = 'passthrough')

step2 = XGBRegressor(n_estimators = 200)
pipe = Pipeline([('step1',step1),('step2',step2)])

# Training the model stored in Pipe
pipe.fit(X_train , y_train)
y_pred = pipe.predict(X_test) #Storing the Pred made by the machine
print("R_2 Score for XGBRegressor",r2_score(y_test,y_pred))
print("Mean Absoluute Error for XGBRegressor",mean_absolute_error(y_test,y_pred))
print("Mean Squared Error for XGBRegressor",mean_squared_error(y_test,y_pred))

R_2 Score for XGBRegressor 0.7939687967300415
Mean Absoluute Error for XGBRegressor 21030.310546875
Mean Squared Error for XGBRegressor 1280064256.0

In [41]:
import joblib

joblib.dump(pipe, "model.pkl")

print("Model saved successfully!")

Model saved successfully!